apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1
spec:
replicas: 2
selector:
  matchLabels: 
    app: task1-app
strategy:
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 50%
template:
  metadata:
    labels:
      app:task1-app
  spec:
    containers:
    - name: task1
      image: jasonatkins/task1jenk:v{{version}}
      env:
        - name: YOUR_NAME
          value: {{YOUR_NAME}}  
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels: task1-app
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - port: 5500
      protocol: TCP
      
      
