apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
  - name: app
    image: jasonatkins/task1jenk:latest
    env:
      - name: YOUR_NAME
        valueFrom:
        secretKeyRef:
          name: your-name-secret
          key: yourname   
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - port: 5500
      protocol: TCP
      
      
